name: Manual Workflow
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 pytest

      - name: Verify installed packages
        run: pip list

      - name: Run pytest
        run: |
          echo "Running pytest..."
          pytest

      - name: Run flake8
        run: |
          echo "Running flake8..."
          flake8 .
